version: '3.8'
services:
  db:
    container_name: ophis_db
    image: postgres:14
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
